const express=require('express'), http=require('http'), path=require('path'), crypto=require('crypto');
const {Server}=require('socket.io');
const app=express(), server=http.createServer(app), io=new Server(server,{pingTimeout:30000,pingInterval:10000});
app.use(express.static(__dirname));
const rooms=new Map(), CATS=['Country','Pop Star','Actor','TV Programme','Film'], LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const roomCode=()=>{const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let x='';do{x='';for(let i=0;i<4;i++)x+=c[Math.floor(Math.random()*c.length)]}while(rooms.has(x));return x};
const token=()=>crypto.randomBytes(12).toString('hex');
function pub(r){return{code:r.code,hostToken:r.hostToken,phase:r.phase,round:r.round,letter:r.letter,players:[...r.players.values()].map(p=>({token:p.token,name:p.name,score:p.score,roundScore:p.roundScore||0,finished:p.finished,connected:!!p.socketId})),categories:CATS,finalCountdownEndsAt:r.finalCountdownEndsAt||null,lastSheets:r.lastSheets||{}}}
function emit(r){io.to(r.code).emit('roomState',pub(r))}
function bind(socket,r,p){p.socketId=socket.id;socket.join(r.code);socket.data.room=r.code;socket.data.token=p.token;r.lastActive=Date.now()}
function endAnswers(r){if(r.phase!=='answers')return;r.phase='review';r.finalCountdownEndsAt=null;const sheets={};for(const p of r.players.values())sheets[p.token]={name:p.name,answers:p.answers||[]};r.lastSheets=sheets;io.to(r.code).emit('reviewState',{room:pub(r),sheets});emit(r)}
io.on('connection',socket=>{
 socket.on('createRoom',({name},cb)=>{const code=roomCode(),t=token();const r={code,hostToken:t,phase:'lobby',round:1,letter:null,players:new Map(),finalCountdownEndsAt:null,lastActive:Date.now()};const p={token:t,name:(name||'Host').trim().slice(0,20),score:0,roundScore:0,answers:[],finished:false,socketId:null};r.players.set(t,p);rooms.set(code,r);bind(socket,r,p);cb?.({ok:true,code,token:t});emit(r)});
 socket.on('joinRoom',({code,name},cb)=>{code=(code||'').trim().toUpperCase();const r=rooms.get(code);if(!r)return cb?.({ok:false,error:'Room not found. Check the 4-character code and try again.'});if(r.phase!=='lobby')return cb?.({ok:false,error:'Game already started'});if(r.players.size>=8)return cb?.({ok:false,error:'Room is full'});const t=token(),p={token:t,name:(name||'Player').trim().slice(0,20),score:0,roundScore:0,answers:[],finished:false,socketId:null};r.players.set(t,p);bind(socket,r,p);cb?.({ok:true,code,token:t});emit(r)});
 socket.on('reconnectRoom',({code,token:t},cb)=>{const r=rooms.get((code||'').toUpperCase()),p=r?.players.get(t);if(!r||!p)return cb?.({ok:false});bind(socket,r,p);cb?.({ok:true,token:t});emit(r);if(r.phase==='answers')socket.emit('roundStarted',{letter:r.letter,categories:CATS});if(r.phase==='review'){const sheets={};for(const x of r.players.values())sheets[x.token]={name:x.name,answers:x.answers||[]};socket.emit('reviewState',{room:pub(r),sheets})}});
 socket.on('startGame',(_,cb)=>{const r=rooms.get(socket.data.room);if(!r||r.hostToken!==socket.data.token)return;if(r.players.size<2)return cb?.({ok:false,error:'Need at least 2 players'});r.phase='letter';r.letter=null;for(const p of r.players.values()){p.answers=[];p.finished=false;p.roundScore=0}emit(r);cb?.({ok:true})});
 socket.on('revealLetter',()=>{const r=rooms.get(socket.data.room);if(!r||r.hostToken!==socket.data.token||r.phase!=='letter')return;r.letter=LETTERS[Math.floor(Math.random()*26)];r.phase='answers';r.finalCountdownEndsAt=null;for(const p of r.players.values()){p.answers=[];p.finished=false;p.roundScore=0}emit(r);io.to(r.code).emit('roundStarted',{letter:r.letter,categories:CATS})});
 socket.on('submitAnswers',({answers},cb)=>{const r=rooms.get(socket.data.room),p=r?.players.get(socket.data.token);if(!r||!p||r.phase!=='answers')return cb?.({ok:false});p.answers=CATS.map((_,i)=>String((answers||[])[i]||'').trim().slice(0,80));p.finished=true;if(!r.finalCountdownEndsAt){r.finalCountdownEndsAt=Date.now()+10000;io.to(r.code).emit('finalCountdown',{endsAt:r.finalCountdownEndsAt,finisher:p.name});setTimeout(()=>{const x=rooms.get(r.code);if(x)endAnswers(x)},10100)}emit(r);cb?.({ok:true})});
 socket.on('scoreRound',({decisions},cb)=>{const r=rooms.get(socket.data.room);if(!r||r.hostToken!==socket.data.token||r.phase!=='review')return;for(const p of r.players.values())p.roundScore=0;for(let ci=0;ci<CATS.length;ci++){const f={};for(const p of r.players.values()){const a=(p.answers||[])[ci]||'',k=`${p.token}|${ci}`,v=decisions&&k in decisions?!!decisions[k]:(!!a&&a[0].toUpperCase()===r.letter);if(v)f[a.toLowerCase()]=(f[a.toLowerCase()]||0)+1}for(const p of r.players.values()){const a=(p.answers||[])[ci]||'',k=`${p.token}|${ci}`,v=decisions&&k in decisions?!!decisions[k]:(!!a&&a[0].toUpperCase()===r.letter);if(v){const pts=f[a.toLowerCase()]>1?5:10;p.score+=pts;p.roundScore+=pts}}}r.phase='scores';emit(r);cb?.({ok:true})});
 socket.on('nextRound',()=>{const r=rooms.get(socket.data.room);if(!r||r.hostToken!==socket.data.token)return;r.round++;r.phase='letter';r.letter=null;r.finalCountdownEndsAt=null;for(const p of r.players.values()){p.answers=[];p.finished=false;p.roundScore=0}emit(r)});
 socket.on('leaveRoom',(_,cb)=>{const r=rooms.get(socket.data.room),t=socket.data.token;if(!r||!t){cb?.({ok:true});return}const wasHost=r.hostToken===t;r.players.delete(t);socket.leave(r.code);socket.data.room=null;socket.data.token=null;if(r.players.size===0){rooms.delete(r.code)}else if(wasHost){const next=[...r.players.values()][0];r.hostToken=next.token;emit(r)}else emit(r);cb?.({ok:true})});
 socket.on('endGame',()=>{const r=rooms.get(socket.data.room);if(!r||r.hostToken!==socket.data.token)return;const ps=[...r.players.values()],top=ps.length?Math.max(...ps.map(p=>p.score)):0,w=ps.filter(p=>p.score===top);const message=w.length===1?`Game over — ${w[0].name} wins with ${top} points!`:`Game over — tie between ${w.map(p=>p.name).join(', ')} on ${top} points.`;io.to(r.code).emit('gameEnded',{message});rooms.delete(r.code)});
 socket.on('disconnect',()=>{const r=rooms.get(socket.data.room),p=r?.players.get(socket.data.token);if(!r||!p)return;if(p.socketId===socket.id)p.socketId=null;r.lastActive=Date.now();emit(r)});
});
setInterval(()=>{const cutoff=Date.now()-30*60*1000;for(const [c,r] of rooms)if(r.lastActive<cutoff&&![...r.players.values()].some(p=>p.socketId))rooms.delete(c)},60000);
server.listen(process.env.PORT||3000,()=>console.log('CLASH 26 ready'));
